"""Idempotent create-or-converge for config-management tools (Ansible,
Puppet, Chef, GitOps).

Each upsert resolves the resource by its natural key within the actor's
tenant, computes the diff against the provided fields (absent fields are
left untouched), and either creates, converges, or reports `unchanged` —
speaking Ansible's native changed/unchanged vocabulary. Secrets are only
ever returned on create and never regenerated by an update (credentials can
opt into replacement with update_secret="always").

`dry=True` computes the same report without touching the database — check
mode. The `planned` dict lets /v1/apply resolve references to resources
earlier items in the same document would create.

All mutations run through the existing crud functions, so permissions,
guards (last-admin, builtin roles, keystore restrictions) and the audit
trail behave exactly as the plain endpoints.
"""

from dataclasses import dataclass, field

from fastapi import HTTPException, Request
from sqlalchemy import select
from sqlalchemy.orm import Session

from . import crud
from .authz import Actor
from .models import Agent, DownstreamCredential, GatewayRoute


@dataclass
class Result:
    kind: str
    key: str
    action: str  # created | updated | unchanged
    changes: dict = field(default_factory=dict)
    secret: str | None = None  # one-time, create only
    obj: object | None = None

    @property
    def changed(self) -> bool:
        return self.action != "unchanged"

    def report(self) -> dict:
        out = {"kind": self.kind, "key": self.key, "action": self.action,
               "changes": self.changes}
        return out


def _planned(planned: dict | None, kind: str) -> set:
    return (planned or {}).get(kind, set())


def _tenant(db: Session, actor: Actor):
    """Resolve (creating if needed) the actor's tenant and backfill the
    actor's tenant_id: on a brand-new database the auth-time snapshot is
    None until the first write creates the tenant, and /v1/apply performs
    lookups and grant visibility checks in the same request."""
    tenant = crud.actor_tenant(db, actor)
    if actor.tenant_id is None:
        actor.tenant_id = tenant.id
    return tenant


# ------------------------------------------------------------------- users


def upsert_user(db: Session, request: Request, actor: Actor, spec: dict,
                dry: bool = False, planned: dict | None = None) -> Result:
    email = (spec.get("email") or "").strip().lower()
    if not email:
        raise HTTPException(422, "email is required")
    tenant = _tenant(db, actor)
    current = crud.find_principal_by_email(db, tenant, email)
    if current is not None and current.deleted_at is not None:
        current = None  # soft-deleted: treat as absent (create revives via SCIM only)

    if current is None:
        role = spec.get("role") or "agent-manager"
        if dry:
            return Result("user", email, "created",
                          {"role": role, "display_name": spec.get("display_name", "")})
        principal = crud.create_principal(
            db, request, actor.label, email=email,
            display_name=spec.get("display_name") or "", role=role, tenant=tenant,
        )
        return Result("user", email, "created", {"role": role}, obj=principal)

    changes: dict = {}
    if spec.get("display_name") is not None and spec["display_name"] != current.display_name:
        changes["display_name"] = [current.display_name, spec["display_name"]]
    if spec.get("role") is not None and (
        current.role is None or spec["role"] != current.role.name
    ):
        changes["role"] = [current.role.name if current.role else None, spec["role"]]
    if spec.get("active") is not None and bool(spec["active"]) != current.active:
        changes["active"] = [current.active, bool(spec["active"])]
    if not changes:
        return Result("user", email, "unchanged", obj=current)
    if dry:
        return Result("user", email, "updated", changes)
    principal = crud.update_principal(
        db, request, actor, current.id,
        display_name=spec.get("display_name"), role=spec.get("role"),
        active=spec.get("active"),
    )
    return Result("user", email, "updated", changes, obj=principal)


# ------------------------------------------------------------------- roles


def upsert_role(db: Session, request: Request, actor: Actor, spec: dict,
                dry: bool = False, planned: dict | None = None) -> Result:
    name = (spec.get("name") or "").strip()
    if not name:
        raise HTTPException(422, "role name is required")
    tenant = _tenant(db, actor)
    current = crud.get_role(db, tenant, name)

    if current is None:
        if dry:
            return Result("role", name, "created",
                          {"permissions": spec.get("permissions") or []})
        role = crud.create_role(
            db, request, actor, name=name,
            description=spec.get("description") or "",
            permissions=spec.get("permissions") or [],
        )
        return Result("role", name, "created",
                      {"permissions": role.permissions}, obj=role)

    changes: dict = {}
    if spec.get("description") is not None and spec["description"] != current.description:
        changes["description"] = True
    if spec.get("permissions") is not None and spec["permissions"] != (current.permissions or []):
        changes["permissions"] = [current.permissions, spec["permissions"]]
    if not changes:
        return Result("role", name, "unchanged", obj=current)
    if dry:
        return Result("role", name, "updated", changes)
    role = crud.update_role(
        db, request, actor, current.id,
        description=spec.get("description"), permissions=spec.get("permissions"),
    )
    return Result("role", name, "updated", changes, obj=role)


# ------------------------------------------------------------- credentials


def _agent_by_name(db: Session, actor: Actor, name: str) -> Agent | None:
    return db.scalar(
        select(Agent).where(Agent.tenant_id == actor.tenant_id, Agent.name == name)
    )


def _resolve_grant_agents(db: Session, actor: Actor, names: list[str],
                          dry: bool, planned: dict | None) -> dict[str, Agent | None]:
    """name -> Agent (or None when dry and the agent is planned-but-not-created)."""
    out: dict[str, Agent | None] = {}
    missing = []
    for name in names:
        agent = _agent_by_name(db, actor, name)
        if agent is None:
            if dry and name in _planned(planned, "agents"):
                out[name] = None
                continue
            missing.append(name)
        else:
            out[name] = agent
    if missing:
        raise HTTPException(422, f"Unknown agent(s) for grants: {', '.join(sorted(missing))}")
    return out


def _converge_grants(db, request, actor, *, desired_names, current_grants,
                     grant_fn, revoke_fn, resource_id, dry, planned) -> dict | None:
    desired = _resolve_grant_agents(db, actor, desired_names, dry, planned)
    current_by_id = {g.agent.id: g.agent.name for g in current_grants if g.agent is not None}
    desired_ids = {a.id for a in desired.values() if a is not None}
    to_add = [a for a in desired.values() if a is not None and a.id not in current_by_id]
    to_remove = [aid for aid in current_by_id if aid not in desired_ids]
    planned_only = [n for n, a in desired.items() if a is None]

    if not to_add and not to_remove and not planned_only:
        return None
    change = [sorted(current_by_id.values()), sorted(desired_names)]
    if dry:
        return change
    for agent in to_add:
        grant_fn(db, request, actor, resource_id, agent.id)
    for agent_id in to_remove:
        revoke_fn(db, request, actor, resource_id, agent_id)
    return change


def upsert_credential(db: Session, request: Request, actor: Actor, spec: dict,
                      dry: bool = False, planned: dict | None = None) -> Result:
    name = (spec.get("name") or "").strip()
    if not name:
        raise HTTPException(422, "credential name is required")
    tenant = _tenant(db, actor)
    current = db.scalar(
        select(DownstreamCredential).where(
            DownstreamCredential.tenant_id == tenant.id,
            DownstreamCredential.name == name,
        )
    )
    update_secret = (spec.get("update_secret") or "on_create").strip().lower()
    if update_secret not in ("on_create", "always"):
        raise HTTPException(422, "update_secret must be on_create or always")

    if current is None:
        if not spec.get("secret"):
            raise HTTPException(422, f"secret is required to create credential '{name}'")
        changes: dict = {"secret": "set"}
        if dry:
            return Result("credential", name, "created", changes)
        cred = crud.create_credential(
            db, request, actor, name=name,
            description=spec.get("description") or "",
            secret=spec["secret"], owner_email=spec.get("owner_email"),
        )
        result = Result("credential", name, "created", changes, obj=cred)
        if spec.get("granted_agents") is not None:
            grant_change = _converge_grants(
                db, request, actor, desired_names=spec["granted_agents"],
                current_grants=[], grant_fn=crud.grant_credential,
                revoke_fn=crud.revoke_credential_grant, resource_id=cred.id,
                dry=False, planned=planned,
            )
            if grant_change:
                result.changes["granted_agents"] = grant_change
        return result

    changes = {}
    if spec.get("description") is not None and spec["description"] != current.description:
        changes["description"] = True
    if spec.get("secret") and update_secret == "always":
        changes["secret"] = "replaced"
    grant_change = None
    if spec.get("granted_agents") is not None:
        grant_change = _converge_grants(
            db, request, actor, desired_names=spec["granted_agents"],
            current_grants=list(current.grants),
            grant_fn=crud.grant_credential, revoke_fn=crud.revoke_credential_grant,
            resource_id=current.id, dry=dry, planned=planned,
        )
        if grant_change:
            changes["granted_agents"] = grant_change
    if not changes:
        return Result("credential", name, "unchanged", obj=current)
    if dry:
        return Result("credential", name, "updated", changes)
    if spec.get("description") is not None or "secret" in changes:
        crud.update_credential(
            db, request, actor, current.id,
            description=spec.get("description"),
            secret=spec["secret"] if "secret" in changes else None,
        )
    return Result("credential", name, "updated", changes, obj=current)


# ------------------------------------------------------------------ agents


def upsert_agent(db: Session, request: Request, actor: Actor, spec: dict,
                 dry: bool = False, planned: dict | None = None) -> Result:
    name = (spec.get("name") or "").strip()
    if not name:
        raise HTTPException(422, "agent name is required")
    _tenant(db, actor)
    current = _agent_by_name(db, actor, name)

    if current is None:
        if dry:
            return Result("agent", name, "created",
                          {"scopes": spec.get("allowed_scopes") or []})
        agent, secret = crud.create_agent(
            db, request, actor, name=name,
            description=spec.get("description") or "",
            allowed_scopes=spec.get("allowed_scopes"),
            allowed_resources=spec.get("allowed_resources"),
            owner_email=spec.get("owner_email"),
            keyring=spec.get("keyring") or "default",
            federated_issuer=spec.get("federated_issuer"),
            federated_subject=spec.get("federated_subject"),
        )
        return Result("agent", name, "created",
                      {"scopes": agent.allowed_scopes}, secret=secret, obj=agent)

    changes: dict = {}
    if spec.get("description") is not None and spec["description"] != current.description:
        changes["description"] = True
    if spec.get("allowed_scopes") is not None and spec["allowed_scopes"] != (current.allowed_scopes or []):
        changes["allowed_scopes"] = [current.allowed_scopes, spec["allowed_scopes"]]
    if spec.get("allowed_resources") is not None and spec["allowed_resources"] != (current.allowed_resources or []):
        changes["allowed_resources"] = [current.allowed_resources, spec["allowed_resources"]]
    if spec.get("keyring") is not None and spec["keyring"] != (current.keyring or "default"):
        changes["keyring"] = [current.keyring, spec["keyring"]]
    fed_i, fed_s = spec.get("federated_issuer"), spec.get("federated_subject")
    if (fed_i is not None or fed_s is not None) and (
        (fed_i or None), (fed_s or None)
    ) != (current.federated_issuer, current.federated_subject):
        changes["federated"] = [bool(current.federated_issuer), bool(fed_i)]
    if not changes:
        return Result("agent", name, "unchanged", obj=current)
    if dry:
        return Result("agent", name, "updated", changes)
    agent = crud.update_agent(
        db, request, actor, current.id,
        description=spec.get("description"),
        allowed_scopes=spec.get("allowed_scopes"),
        allowed_resources=spec.get("allowed_resources"),
        keyring=spec.get("keyring"),
        federated_issuer=fed_i, federated_subject=fed_s,
    )
    return Result("agent", name, "updated", changes, obj=agent)


# ------------------------------------------------------------------ routes


def upsert_route(db: Session, request: Request, actor: Actor, spec: dict,
                 dry: bool = False, planned: dict | None = None) -> Result:
    from . import gateway_policy as gp

    slug = (spec.get("slug") or "").strip()
    if not slug:
        raise HTTPException(422, "route slug is required")
    tenant = _tenant(db, actor)
    current = db.scalar(
        select(GatewayRoute).where(
            GatewayRoute.tenant_id == tenant.id, GatewayRoute.slug == slug
        )
    )

    if current is None:
        missing = [f for f in ("upstream_base", "credential_name") if not spec.get(f)]
        if missing:
            raise HTTPException(
                422, f"route '{slug}' create requires: {', '.join(missing)}"
            )
        if dry:
            cred = spec["credential_name"]
            if cred not in _planned(planned, "credentials"):
                exists = db.scalar(select(DownstreamCredential).where(
                    DownstreamCredential.tenant_id == tenant.id,
                    DownstreamCredential.name == cred))
                if exists is None:
                    raise HTTPException(422, f"Unknown credential '{cred}'")
            return Result("route", slug, "created",
                          {"upstream": spec["upstream_base"]})
        route = crud.create_route(
            db, request, actor, slug=slug,
            description=spec.get("description") or "",
            icon=spec.get("icon") or "",
            upstream_base=spec["upstream_base"],
            credential_name=spec["credential_name"],
            inject_mode=spec.get("inject_mode") or "bearer",
            inject_header=spec.get("inject_header") or "Authorization",
            allowed_methods=spec.get("allowed_methods"),
            allowed_path_prefixes=spec.get("allowed_path_prefixes"),
            owner_email=spec.get("owner_email"),
            rate_limit_per_minute=spec.get("rate_limit_per_minute") or 0,
            daily_quota=spec.get("daily_quota") or 0,
            verify_tls=spec.get("verify_tls", True),
            git_http=spec.get("git_http", False),
        )
        result = Result("route", slug, "created",
                        {"upstream": route.upstream_base}, obj=route)
        if spec.get("granted_agents") is not None:
            grant_change = _converge_grants(
                db, request, actor, desired_names=spec["granted_agents"],
                current_grants=[], grant_fn=crud.grant_route,
                revoke_fn=crud.revoke_route_grant, resource_id=route.id,
                dry=False, planned=planned,
            )
            if grant_change:
                result.changes["granted_agents"] = grant_change
        return result

    changes: dict = {}
    simple = {
        "description": current.description,
        "icon": current.icon,
        "upstream_base": current.upstream_base,
        "inject_mode": current.inject_mode,
        "inject_header": current.inject_header,
        "rate_limit_per_minute": current.rate_limit_per_minute or 0,
        "daily_quota": current.daily_quota or 0,
    }
    for fld, cur in simple.items():
        if spec.get(fld) is not None and spec[fld] != cur:
            changes[fld] = [cur, spec[fld]]
    if spec.get("active") is not None and bool(spec["active"]) != current.active:
        changes["active"] = [current.active, bool(spec["active"])]
    if spec.get("verify_tls") is not None and bool(spec["verify_tls"]) != current.verify_tls:
        changes["verify_tls"] = [current.verify_tls, bool(spec["verify_tls"])]
    if spec.get("git_http") is not None and bool(spec["git_http"]) != current.git_http:
        changes["git_http"] = [current.git_http, bool(spec["git_http"])]
    if spec.get("allowed_methods") is not None:
        nm = gp.normalize_methods(spec["allowed_methods"])
        if nm != (current.allowed_methods or []):
            changes["allowed_methods"] = [current.allowed_methods, nm]
    if spec.get("allowed_path_prefixes") is not None:
        np = gp.normalize_prefixes(spec["allowed_path_prefixes"])
        if np != (current.allowed_path_prefixes or []):
            changes["allowed_path_prefixes"] = [current.allowed_path_prefixes, np]
    if spec.get("credential_name") is not None and (
        current.credential is None or spec["credential_name"] != current.credential.name
    ):
        changes["credential"] = [
            current.credential.name if current.credential else None,
            spec["credential_name"],
        ]
    grant_change = None
    if spec.get("granted_agents") is not None:
        grant_change = _converge_grants(
            db, request, actor, desired_names=spec["granted_agents"],
            current_grants=list(current.grants),
            grant_fn=crud.grant_route, revoke_fn=crud.revoke_route_grant,
            resource_id=current.id, dry=dry, planned=planned,
        )
        if grant_change:
            changes["granted_agents"] = grant_change
    if not changes:
        return Result("route", slug, "unchanged", obj=current)
    if dry:
        return Result("route", slug, "updated", changes)
    non_grant = {k for k in changes if k != "granted_agents"}
    if non_grant:
        crud.update_route(
            db, request, actor, current.id,
            description=spec.get("description"),
            upstream_base=spec.get("upstream_base"),
            inject_mode=spec.get("inject_mode"),
            inject_header=spec.get("inject_header"),
            allowed_methods=spec.get("allowed_methods"),
            allowed_path_prefixes=spec.get("allowed_path_prefixes"),
            active=spec.get("active"),
            rate_limit_per_minute=spec.get("rate_limit_per_minute"),
            daily_quota=spec.get("daily_quota"),
            credential_name=spec.get("credential_name"),
            verify_tls=spec.get("verify_tls"),
            git_http=spec.get("git_http"),
            icon=spec.get("icon"),
        )
    return Result("route", slug, "updated", changes, obj=current)
